name: "Turbo Test Coverage"
description: "Turbo Test Coverage"

inputs:
  rootDir:
    description: 'Root directory of the repo'
    default: './'
    required: false
  workspaces:
    description: 'List of workspaces that needs to be considered for coverage'
    required: true

outputs:
  coverage_breakdown:
    description: "Test coverage breakdown for the workspaces"

runs:
  using: "node16"
  main: "dist/index.js"
